from __future__ import annotations

from enum import Enum


class SystemMode(str, Enum):
    BOOTING = "BOOTING"
    READ_ONLY = "READ_ONLY"
    PAPER = "PAPER"
    SHADOW = "SHADOW"
    ARMED = "ARMED"
    LIVE = "LIVE"
    HALTED = "HALTED"
    KILLED = "KILLED"


class KillMode(str, Enum):
    STOP_NEW_ORDERS = "STOP_NEW_ORDERS"
    CANCEL_OPEN_ORDERS = "CANCEL_OPEN_ORDERS"
    LIQUIDATE_POSITIONS = "LIQUIDATE_POSITIONS"


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    DRAFT = "DRAFT"
    RISK_APPROVED = "RISK_APPROVED"
    READY = "READY"
    SUBMITTING = "SUBMITTING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"
    RECONCILING = "RECONCILING"
    MANUAL_REVIEW = "MANUAL_REVIEW"
